export const addDoctorInputs = [
  {
    label: 'Email',
    id: 'email',
    type: 'text',
    placeholder: 'sample@gmail.com',
    required: true,
  },
  {
    label: 'Password',
    id: 'password',
    type: 'password',
    placeholder: 'Password',
    required: true,
  },
  {
    label: 'Name',
    id: 'full_name',
    type: 'text',
    placeholder: 'Name',
    required: true,
  },
  {
    label: 'Age',
    id: 'age',
    type: 'number',
    placeholder: 'Age',
    required: true,
  },
  {
    label: 'Sex',
    id: 'sex',
    type: 'select',
    options: [
      { value: 'male', label: 'Male' },
      { value: 'female', label: 'Female' },
    ],
    placeholder: 'Select sex',
    required: true,
  },
  {
    label: 'Phone',
    id: 'phone_number',
    type: 'number',
    placeholder: 'e.g. 09xxxxxxxxx',
  },
  {
    label: 'Address',
    id: 'address',
    type: 'text',
    placeholder: 'Address',
  },
  {
    label: 'Specialization',
    id: 'specialization',
    type: 'text',
    placeholder: 'e.g. Retina Specialist',
  },
  {
    label: 'License Number',
    id: 'license_number',
    type: 'text',
    placeholder: 'e.g. PH-MED-12345',
  },
  {
    label: 'Years of Experience',
    id: 'years_experience',
    type: 'number',
    placeholder: 'years of experience',
  },
  {
    label: 'Professional Title',
    id: 'professional_title',
    type: 'text',
    placeholder: 'e.g. MD, DO',
  },
  {
    label: 'Clinic',
    id: 'clinic_name',
    type: 'text',
    placeholder: 'e.g. Sample Health Center',
  },
]
