export const addPatientInputs = [
  {
    label: 'Email',
    id: 'email',
    type: 'email',
    placeholder: 'sample@gmail.com',
    required: true,
  },
  {
    label: 'Name',
    id: 'full_name',
    type: 'text',
    placeholder: "Enter patient's name",
    required: true,
  },
  {
    label: 'Age',
    id: 'age',
    type: 'number',
    placeholder: "Enter patient's age",
    required: true,
  },
  {
    label: 'Sex',
    id: 'sex',
    type: 'select',
    options: [
      { value: '0', label: 'Male' },
      { value: '1', label: 'Female' },
    ],
    placeholder: 'Select sex',
    required: true,
  },
  {
    label: 'Birthday',
    id: 'birthday',
    type: 'date',
    placeholder: "Enter patient's birthday",
    required: true,
  },
  {
    label: 'Phone',
    id: 'phone_number',
    type: 'number',
    placeholder: 'e.g. 09xxxxxxxxx',
    required: true,
  },
  {
    label: 'Address',
    id: 'address',
    type: 'text',
    placeholder: "Enter patient's address",
    required: true,
  },
  {
    label: 'Diabetic?',
    id: 'diabetic',
    type: 'select',
    options: [
      { value: '1', label: 'Yes' },
      { value: '0', label: 'No' },
    ],
    placeholder: 'Select option',
    required: true,
  },
  {
    label: 'Smoking?',
    id: 'smoking',
    type: 'select',
    options: [
      { value: '1', label: 'Yes' },
      { value: '0', label: 'No' },
    ],
    placeholder: 'Select option',
    required: true,
  },
  {
    label: 'Hypertensive?',
    id: 'hypertension',
    type: 'select',
    options: [
      { value: '1', label: 'Yes' },
      { value: '0', label: 'No' },
    ],
    placeholder: 'Select option',
    required: true,
  },
  {
    label: 'Stroke History',
    id: 'stroke_history',
    type: 'select',
    options: [
      { value: '1', label: 'Yes' },
      { value: '0', label: 'No' },
    ],
    placeholder: 'Select option',
    required: true,
  },
  {
    label: 'BP Systolic',
    id: 'bp_systolic',
    type: 'number',
    placeholder: 'Enter here',
    required: true,
  },
  {
    label: 'BP Diastolic',
    id: 'bp_diastolic',
    type: 'number',
    placeholder: 'Enter here',
    required: true,
  },
]
